service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

plugins:
  - serverless-step-functions
  - serverless-offline

layers:
  clamAvLayer:
    description: 'clamav layer with python 3.12'
    package:
      artifact: ./packages/lambda_clamav_arm.zip

functions:
  helloFunction:
    handler: handler.hello
    events:
      - http:
          path: hello12
          method: get
    # layers:
    #   - Ref: ClamAvLayerLambdaLayer

stepFunctions:
  stateMachines:
    WorkflowOne:
      name: MyFirstStateMachine
      definition: ${file(./step-functions/workflow1.yml)}

    WorkflowTwo:
      name: MySecondStateMachine
      definition: ${file(./step-functions/workflow2.yml)}

