service: my-service-new

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

plugins:
  - serverless-step-functions
  - serverless-offline

functions:
  helloFunction:
    handler: handler.hello
    name: helloFunctionName 
    events:
      - http:
          path: hello12
          method: get
    layers:
      - Ref: ClamAvLayer1LambdaLayer
      
  helloFunction2:
    handler: handler.hello
    name: helloFunctionName2
    events:
      - http:
          path: hello124
          method: get

# stepFunctions:
#   stateMachines:
#     WorkflowOne:
#       name: MyFirstStateMachine
#       definition: ${file(./step-functions/workflow1.yml)}

#     WorkflowTwo:
#       name: MySecondStateMachine
#       definition: ${file(./step-functions/workflow2.yml)}

layers:
  clamAvLayer1:
    description: 'clamav layer with python 3.12'
    package:
      artifact: ./packages/lambda_clamav_arm.zip
    compatibleRuntimes:
      - python3.12